### ISSUE TITLE
please consider droppping the "BSD" reference... the exception nullifies what we expect of BSD license

### ISSUE THREAD

**Issue by jeske** [nepluno/libwetcloth#1]
Please consider renaming it "free for non-commercial use", or "free for academic use" and remove reference to the BSD license.

The non-commerical use clause makes this incompatible with the LGPL, and GPL, which means it's probably only usable for academic experimentation.

**Comment by raymondyfei** [comment]
Thanks for the comment. We've revised the terms regarding to the BSD license and no longer claim we're under it. Alternative licensing terms are available by contacting the faculty or technology ventures.
