### ISSUE TITLE
Compile error on Linux Mint 19 Tara

### ISSUE THREAD

**Issue by goofoo** [nepluno/libwetcloth#2]
Hi i have a problem with compile  on linux mint 19:
/usr/bin/x86_64-linux-gnu-ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglut.so: undefined reference to symbol 'XCreateBitmapFromData'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
libWetCloth/CMakeFiles/libWetCloth.dir/build.make:810: recipe for target 'libWetCloth/libWetCloth' failed
make[2]: *** [libWetCloth/libWetCloth] Error 1
CMakeFiles/Makefile2:90: recipe for target 'libWetCloth/CMakeFiles/libWetCloth.dir/all' failed
make[1]: *** [libWetCloth/CMakeFiles/libWetCloth.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Big thanks.

**Comment by raymondyfei** [comment]
It seems your libX11 is incomplete. Maybe this post would help you.

https://askubuntu.com/questions/605483/not-able-to-make-successfully-undefined-reference-to-symbol-xcreatebitmapfrom/605518#605518
