### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nepluno/libwetcloth#3]
I would like to point out that identifiers like “[`__SCENE_STEPPER__`](https://github.com/nepluno/libwetcloth/blob/439e93f8bc9950049bc45e4dca9ff30397e7fe7a/libWetCloth/Core/SceneStepper.h#L9 "Update candidate")” and “[`__WET_CLOTH_CORE_H__`](https://github.com/nepluno/libwetcloth/blob/439e93f8bc9950049bc45e4dca9ff30397e7fe7a/libWetCloth/Core/WetClothCore.h#L10 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by raymondyfei** [comment]
Sure. Resolved.
