### ISSUE TITLE
CMake error on ubuntu20.04

### ISSUE THREAD

**Issue by MaxZZG** [nepluno/libwetcloth#4]
I recently compiled libWetCloth using ubuntu 20.04 but CMake reported the following error:

`CMake Error at libWetCloth/App/CMakeLists.txt:29 (find_package):
  By not providing "FindFREEGLUT.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FREEGLUT",
  but CMake did not find one.
  Could not find a package configuration file provided by "FREEGLUT" with any
  of the following names:
    FREEGLUTConfig.cmake
    freeglut-config.cmake
  Add the installation prefix of "FREEGLUT" to CMAKE_PREFIX_PATH or set
  "FREEGLUT_DIR" to a directory containing one of the above files.  If
  "FREEGLUT" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!`

It looks like FindFreeGLUT.cmake should be FindFREEGLUT.cmake in /libwetcloth/cmake. I tried and it works.  Modifying the CMakeLists.txt file also works.

**Comment by raymondyfei** [comment]
Fixed. Thanks!
