### ISSUE TITLE
Little problem when running the demo

### ISSUE THREAD

**Issue by Moqyen** [nepluno/libwetcloth#6]
Hi,
      After completing the compilation on Ubuntu system, I started trying to run the demo. I typed "WetClothApp - s/ When assets/unit_tests/simple.cloth.xml" in terminal and it show "bash: .WetClothApp: There is no such file or directory“. 
      I guess there may be a lack of execution commands. Could you please tell me how to solve this problem？

**Comment by raymondyfei** [comment]
The path after `-s` specifies the file to be loaded, for example, `./WetClothApp -s ../assets/unit_tests/simple_cloth.xml`. Please put the correct file path there.

And please do not file such trivial questions as issues. This is not an issue in the library. Thanks.
